basharovV/musicat

- src/App.svelte
- src/lib/albums/AlbumItem.svelte
- src/lib/library/BottomBar.svelte
- src/lib/library/CassetteLoading.svelte
- src/lib/library/TrackInfoPopup.svelte
- src/lib/sidebar/Seekbar.svelte
- src/lib/sidebar/Sidebar.svelte
- src/lib/views/ArtistsToolkitView.svelte
- src/lib/views/InternetArchiveView.svelte
- src/lib/views/QueueView.svelte
- src/lib/your-music/ContentDropzone.svelte
- src/lib/your-music/LyricsTab.svelte
Hi,
This PR is removing the Sass warnings due to the rule's position.
> fix: remove sass warnings

- src/lib/albums/AlbumItem.svelte
This PR will display the year of the album only if it's present.
> enhance: don't display year when it's missing

- src/lib/views/AlbumsView.svelte
On the Albums view, the PR fixes the button "Scrolling to Now Playing".
> fix: the button "Scrolling to Now Playing" on Albums

- src/lib/views/AlbumsView.svelte
This PR sorts the albums by either:
- `title`
- `artist` and `title`
- `year` and `title`
> feat: sort albums by secondary field

- src/lib/library/ToDeleteHeader.svelte
- src/lib/views/PrunePopup.svelte
This PR is:
- implementing the `Keep All` button
- avoiding to go the `to-delete` view when there is no tracks to delete
- avoiding to add the last track several times when we have reached the end of the queue
> fix: resolve issues when pruning

- src/data/store.ts
This PR adds the missing `await`.
> fix(queue): add missing await

- src/lib/player/Waveform.svelte
This PR fixes a regression from #70...
> fix(waveform): bad variable

- src/data/store.ts
This PR keeps the panels opened after a restart.
> feat: keep panels opened at start

- src/lib/menu/MenuDivider.svelte
- src/lib/sidebar/Sidebar.svelte
- src/lib/ui/Icon.svelte
- src/lib/ui/Input.svelte
- src/theming/themes.ts
This PR improves the theming capability of the sidebar's menu and controls.
> enhance: improve theming

- src/lib/views/AlbumsView.svelte
> fix: Albums grid jumpy behaviour

- src-tauri/src/main.rs
- src-tauri/src/mediakeys/mod.rs
- src-tauri/src/player.rs
- src/lib/player/AudioPlayer.ts
This PR displays the artwork in the macOS command center.
It also adds the **next** command.
> fix(mediakeys): display artwork

- src-tauri/src/main.rs
- src-tauri/src/mediakeys/mod.rs
This PR adds the support for the `previousTrackCommand` and `togglePlayPauseCommand`.
My media keys are also working with those. :sparkles:
> feat(mediakeys): add previous and toggle

- src/lib/player/AudioPlayer.ts
> fix: save position when closing

- src-tauri/src/main.rs
- src-tauri/src/mediakeys/mod.rs
- src/data/store.ts
- src/lib/player/AudioPlayer.ts
- src/lib/player/WebRTCReceiver.ts
This PR fixes the issue of the missing song in the media center at the boot of the app.
> fix(mediakeys): at boot, correctly show current song

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/metadata.rs
- src-tauri/tauri.conf.json
- src/data/LibraryUtils.ts
- src/lib/albums/AlbumMenu.svelte
- src/lib/data/LibraryEnrichers.ts
- src/lib/library/TrackMenu.svelte
- src/lib/player/AudioPlayer.ts
This PR plays external m3u files.
Reference:
- #63
> feat: play external m3u files

- src/App.svelte
- src/data/LibraryUtils.ts
- src/lib/albums/AlbumMenu.svelte
- src/lib/info/MetadataSection.svelte
- src/lib/library/TrackMenu.svelte
This PR restores the favorite flags when re-importing.
> fix: restore favorite on re-import

- src/data/LibraryUtils.ts
This PR avoids to recheck the album for every tracks.
> fix: check album only once when deleting tracks

- src/lib/albums/AlbumMenu.svelte
- src/lib/player/AudioPlayer.ts
This PR uses the correct settings to check the covers.
> fix: use correct settings to check the covers

- src-tauri/src/main.rs
- src-tauri/src/metadata.rs
- src/lib/player/AudioPlayer.ts
This PR loads a M3U in the correct order.
> fix: load m3u in order

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/metadata.rs
This PR will detect the mime-type if it isn't set.
> fix: detect mime-type if not set
