basharovV/musicat

package.json

Needed those to build musicat on manjaro linux

Add  `rollup-plugin-node-polyfills` and `mousetrap`  as dependencies

---

src/data/ArtistsToolkitData.ts
src/data/Cacher.ts
src/data/LibraryImporter.ts
src/data/M3UUtils.ts
src/data/store.ts
src/lib/data/LibraryEnrichers.ts
src/window/EventListener.ts

This PR is fixing the path of the cache dir.
On my system, the `appDataDir()` doesn't finish with a path separator.

fix: correctly build the path of the cache dir

---

src-tauri/tauri.conf.json
src-tauri/tauri.linux.conf.json

This PR adds the CSP rule so that the tags can be read when musicat is built in release mode.
It doesn't change anything in dev mode.
I was getting the error:
```
[Error] Refused to connect to asset://localhost/ because it does not appear in the connect-src directive of the Content Security Policy.
```

fix: update csp & add capability for external drives

---

src/data/store.ts

This PR is fixing a regression from https://github.com/basharovV/musicat/pull/32 (it's missing an `await`). Sorry ;)
It also improves the conditions and avoid to lookup the default directories when not necessary.

fix: add missing await and improve conditions

---

src/lib/library/CanvasLibrary.svelte
src/lib/player/AudioPlayer.ts

This PR avoids to play a song when the search has no results and pressing the <kbd>enter</kbd> key.

fix: don't play a song when search has no results

---

src/App.svelte
src/lib/views/TopBar.svelte

This PR fixes the jumpy album's covers (a 1px flicker) when:
- the queue is opened
- moving the cursor over the covers
The bug is due to the rounding which is not always the same between frames.

fix: jumpy album

---

src/App.svelte

This PR fixes the queue when the waveform is shown.
Here the bug:

fix: resize queue when waveform is displayed

---

src-tauri/tauri.conf.json

This PR allows to use an external drive for:
- the playlists 
- the songbooks
- the scrapbooks

fix: use external drive

---

src-tauri/src/main.rs
src/App.d.ts
src/data/InternetArchiveAPI.ts
src/lib/internet-archive/IAFileBlock.svelte
src/lib/views/InternetArchiveView.svelte

This PR fixes several issues:
- fix url so it can list the collections
- a record can have several originals (https://archive.org/details/lp_sings_heinrich-rehkemper)
- the songs can be private and so can't be listened (https://archive.org/details/lp_nuits-dt-shhrazade_hector-berlioz-maurice-ravel-hildegard-beh)
- `previewSrc` was built with an extra `/` so it wasn't able to be listened
- when downloading, if the target file was on an another drive than the temp file, the `persist` function was failing
A new feature:
- links on the title of the collection and song to open the archive.org page in a browser

fix: resolve issues in the internet archive explorer

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/scrape.rs

This PR opens the links from the wikipedia html into a browser by:
- adding target="_blank"
- adding the prefix "https://en.wikipedia.org" (based on url of the article)

fix: open links into browser with correct url

---

src/lib/views/WikiView.svelte

This PR fixes a regression in #60 which was opening the link when playing or pausing a song.

fix(wiki): don't open link when play/pause

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/player.rs

This PR uses the official WebRTC.
I'm updating it because, on my machine, when paused and from time to time, it loses the connection and the oscilloscope doesn't work anymore. I'm looking into it.
The update doesn't fix the issue but I think it's better to have the latest version.

build: use official webrtc

---

src/data/store.ts
src/lib/sidebar/Sidebar.svelte
src/lib/views/TopBar.svelte

This PR fixes the checks because `$lastWrittenSongs` was `null`.
I've added an optimization by removing the `map()`.

fix: checks

---

src-tauri/gen/schemas/linux-schema.json
src-tauri/src/player.rs

For some reason, the audio device name is None.
Making the trying to play a song crash the entire app
To fix it, I simply just check if there is something in that variable

fix(linux): App crash when `audio_device_name` is `None`

---

package-lock.json
package.json
src/data/store.ts
src/data/storeHelper.ts
src/lib/player/AudioPlayer.ts

This PR fixes the issues of #81 and #83 as discussed in #81.
In `package.json`, I've added the dependency `prettier` to force the version used by the vscode plugin.
No sure why, on my machine, it was using the version `2.8.8` (which seems to remove the trailing commas by default) instead of the a `3.x` which add the trailing commas (what you want based on your comment in https://github.com/basharovV/musicat/commit/82c341a5de0c2c0ba27a52e36bc41256a4ba10de)
It was correctly adding them before...

fix: don't set current song to null

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/metadata.rs
src/App.d.ts
src/App.svelte
src/data/LabelMap.ts
src/data/LibraryUtils.ts
src/lib/info/MetadataSection.svelte
src/lib/info/TrackInfoPopup.svelte
src/lib/player/AudioPlayer.ts
src/lib/ui/ButtonWithIcon.svelte

This PR includes several improvements for the track info popup:
- preserve unsupported tags
- show and update only supported tags
- filter displayed tags based on the selection (hide title when many songs are selected, ...)
- update album when metadata are updated
- split out the metadata section to its own component so it's easier to manage
And about the player on the sidebar:
- moving the handle of the seekbar doesn't automatically play the song
- update the infos when the metadata are updated

enhance: improve track info popup

---

src/data/LibraryUtils.ts
src/lib/albums/AlbumMenu.svelte
src/lib/info/MetadataSection.svelte
src/lib/views/AlbumsView.svelte

This PR fixes:
- show context menu when the album does have any songs (due the next issue)
- correctly *update* album when its title have been changed
I had the issue where an album's title had a space at the end.
- `lofty` keeps the space
- `music-metadata` removes it

fix: album

---

src-tauri/src/main.rs
src-tauri/src/metadata.rs
src-tauri/src/metadata/artwork_cacher.rs
src/App.d.ts
src/lib/sidebar/Sidebar.svelte

This PR reduces the load when playing a song or when importing songs.
The reduction when playing a song is done by:
- loading only the artwork based on new song's field `artworkOrigin` (`Broken|File|Metadata`)
- when the origin isn't known, it will do the full metadata/artwork load
The reductions when importing songs are done by:
- avoiding to load the settings at each artwork search
- avoiding to create the album for each songs, which was implicating:
- looking up for the artwork for each song
- recreating the artwork's cache for each song
The import time is just a little bit improved (148798.698ms, from 159086.326ms)

improve: artwork load

---

src-tauri/src/metadata.rs
src/lib/albums/AlbumDetails.svelte
src/lib/albums/AlbumItem.svelte
src/lib/albums/util.ts
src/lib/library/CanvasLibrary.svelte
src/lib/views/AlbumsView.svelte
src/lib/views/WikiView.svelte

This PR does:
- import the albums with their tracks kept in order
- play first song then load the remaining tracks to add them in the queue
- remove unnecessary load of album's tracks
From my testing:
- the import is a little bit slower (maybe `slice.iter().map(|(_, song)| (*song).clone()).collect()` can be improved)
- the first song loads, in average, in 10ms (from 1000ms)
- the tracks, in 15-500ms
Reference:
- #119

improve: album

---

src-tauri/src/player.rs
src/lib/player/AudioPlayer.ts
src/lib/sidebar/Sidebar.svelte

This PR modifies the end of queue event as:
- reset the current song to null so no infos are displayed when the player is stopped
- the next song is the first song of the queue

improve: at end of queue, next song should be first song

---

src-tauri/src/player.rs

I have an album which generates the error `ERROR Musicat::player:Error probing file: out of bounds` (it can be played on other players).
Currently, the player doesn't play the file and seems to be stuck.
This PR skips to the next song when such error occurs.
I've created an issue on Symphonia (https://github.com/pdeljanov/Symphonia/issues/354)

fix: skip to next song on probe error

---

src-tauri/src/player.rs
src/lib/player/AudioPlayer.ts

This PR is an improvement of #131, it fixes several issues:
- skip the broken song at the end of the current song
- on "play next" button, do not over-increment player's index if the next song is broken

fix: correctly skip song on error
